### ISSUE TITLE
New UI

### ISSUE THREAD

**Issue by sarmadhashmi** [sarmadhashmi/Coursity#10]
All discussion and mockups for new UI should go here.

**Comment by AbeOmor** [comment]
#6 Has some good suggests for future layout

**Comment by AbeOmor** [comment]
<img width="601" alt="screen shot 2016-08-28 at 2 48 28 pm" src="https://cloud.githubusercontent.com/assets/9068012/18035975/e9e244ac-6d2e-11e6-8ddb-34c4ee2c7b44.png">
![coursity2 0_mockup](https://cloud.githubusercontent.com/assets/9068012/18035977/f443c0e2-6d2e-11e6-9478-9b5e112adbd5.png)
